import './globals.css';

import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import Nav from '@/components/ui/nav';
import { ThemeProvider } from '@/components/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='relative overflow-hidden'>
      <body className={inter.className}>
        <Nav />
        <ThemeProvider attribute='class' defaultTheme='dark'>
          <main className='flex min-h-screen flex-col items-center justify-between'>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
